server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core_project
    username: postgres
    password: 777
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true



springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api/docs
api:
  info:
    title: Review Service API
    description: API to fetch review details for product
    version: 1.0.0
    terms-of-service: http://boom.com/terms/
    contact:
      name: Review Service API Team
      email: apiteam@example.com
      url: http://boom.com/team
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: ${server.port}
    url: eliboy.uz
